package cmdcharacter

import (
	"github.com/spf13/cobra"
	"github.com/voilelab/gonovelmaker/internal/llmbackend"
)

type CharacterCmd struct {
	genCharCmd     *GenCharCmd
	genCharCurrCmd *GenCharCurrCmd
	genCharImgCmd  *GenCharImgCmd

	cmd *cobra.Command
}

func NewCharacterCmd(llmBackendMaker llmbackend.LLMBackendMaker) *CharacterCmd {
	c := &CharacterCmd{}
	c.cmd = &cobra.Command{
		Use:     "character",
		Aliases: []string{"char"},
		Short:   "Character management commands",
		Long:    `Manage characters in your novel project. Generate new characters, regenerate existing ones, and create character images.`,
	}

	// Create subcommands
	c.genCharCmd = NewGenCharCmd(llmBackendMaker)
	c.genCharCmd.cmd.Use = "gen"
	c.genCharCmd.cmd.Short = "Generate a new character"
	c.genCharCmd.cmd.Long = `Generates a new character profile using AI based on a prompt.
The character will be created with a profile generated by the LLM backend.`

	c.genCharCurrCmd = NewGenCharCurrCmd(llmBackendMaker)
	c.genCharCurrCmd.cmd.Use = "regen"
	c.genCharCurrCmd.cmd.Short = "Regenerate an existing character"
	c.genCharCurrCmd.cmd.Long = `Regenerates an existing character profile based on the prompt stored in its frontmatter.
The filepath should be relative to the vault root (e.g., "Character/alice.md").`

	c.genCharImgCmd = NewGenCharImgCmd(llmBackendMaker)
	c.genCharImgCmd.cmd.Use = "gen-img"
	c.genCharImgCmd.cmd.Short = "Generate an image for a character"
	c.genCharImgCmd.cmd.Long = `Generates an image for a character based on their profile using OpenAI's DALL-E API.
The image will be downloaded and saved to the Character directory.`

	c.cmd.AddCommand(c.genCharCmd.cmd)
	c.cmd.AddCommand(c.genCharCurrCmd.cmd)
	c.cmd.AddCommand(c.genCharImgCmd.cmd)

	return c
}

func (c *CharacterCmd) Command() *cobra.Command {
	return c.cmd
}
