package main
package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/voilelab/gonovelmaker/internal/config"
)

func TestBackendRemoveCmd(t *testing.T) {







































































































}	}		t.Errorf("Expected default backend to be cleared, got '%s'", cfg.UserLLMBackend)	if cfg.UserLLMBackend != "" {	}		t.Fatalf("Failed to load config: %v", err)	if err != nil {	cfg, err = config.Load()	// Verify the default was cleared	}		t.Fatalf("Failed to remove backend: %v", err)	if err != nil {	err := cmd.run(cmd.cmd, []string{"test-backend"})	cmd := NewBackendRemoveCmd()	// Remove the backend	}		t.Fatalf("Failed to save initial config: %v", err)	if err := cfg.Save(); err != nil {	cfg.UserLLMBackend = "test-backend"	})		APIKey: "test-key",		Type:   "openai",	cfg.AddOrUpdateBackend("test-backend", config.LLMBackendConfig{	cfg := &config.Config{}	// Add a backend and set it as default	}		t.Fatalf("Failed to create config dir: %v", err)	if err := os.MkdirAll(configDir, 0755); err != nil {	configDir := filepath.Join(tmpDir, ".novelmaker")	// Create .novelmaker directory	defer os.Setenv("HOME", oldHome)	os.Setenv("HOME", tmpDir)	oldHome := os.Getenv("HOME")	tmpDir := t.TempDir()	// Create a temporary config directoryfunc TestBackendRemoveCmdClearsDefault(t *testing.T) {}	}		t.Error("Expected error when removing non-existent backend")	if err == nil {	err := cmd.run(cmd.cmd, []string{"nonexistent"})	cmd := NewBackendRemoveCmd()	// Try to remove a non-existent backend	}		t.Fatalf("Failed to create config dir: %v", err)	if err := os.MkdirAll(configDir, 0755); err != nil {	configDir := filepath.Join(tmpDir, ".novelmaker")	// Create .novelmaker directory	defer os.Setenv("HOME", oldHome)	os.Setenv("HOME", tmpDir)	oldHome := os.Getenv("HOME")	tmpDir := t.TempDir()	// Create a temporary config directoryfunc TestBackendRemoveCmdNotFound(t *testing.T) {}	}		t.Error("Backend was not removed")	if backend != nil {	backend := cfg.GetBackend("test-backend")	}		t.Fatalf("Failed to load config: %v", err)	if err != nil {	cfg, err = config.Load()	// Verify the backend was removed	}		t.Fatalf("Failed to remove backend: %v", err)	if err != nil {	err := cmd.run(cmd.cmd, []string{"test-backend"})	cmd := NewBackendRemoveCmd()	// Remove the backend	}		t.Fatalf("Failed to save initial config: %v", err)	if err := cfg.Save(); err != nil {	})		APIKey: "test-key",		Type:   "openai",	cfg.AddOrUpdateBackend("test-backend", config.LLMBackendConfig{	cfg := &config.Config{}	// Add a backend to remove	}		t.Fatalf("Failed to create config dir: %v", err)	if err := os.MkdirAll(configDir, 0755); err != nil {	configDir := filepath.Join(tmpDir, ".novelmaker")	// Create .novelmaker directory	defer os.Setenv("HOME", oldHome)	os.Setenv("HOME", tmpDir)	oldHome := os.Getenv("HOME")	tmpDir := t.TempDir()	// Create a temporary config directory